import { mkdir, readFile, writeFile } from "node:fs/promises";

const manifestUrl = new URL("./render-manifest.json", import.meta.url);
const localCandidatesUrl = new URL("./renderlab-local-candidates.json", import.meta.url);
const outputUrl = new URL("../../src/generated/renderLabPreviewCatalog.ts", import.meta.url);
const manifest = JSON.parse(await readFile(manifestUrl, "utf8"));
const localCandidates = JSON.parse(await readFile(localCandidatesUrl, "utf8"));

const catalog = Object.fromEntries(
  [...manifest.outputs, ...localCandidates.outputs].map((output) => [
    output.id,
    {
      id: output.id,
      phase: output.phase,
      screens: output.screens ?? [],
      kind: output.kind,
      placement: output.placement,
      status: output.unreal?.status ?? output.status ?? "unknown",
      decision: output.review?.decision ?? output.decision,
      note: output.review?.note ?? output.note,
      candidate: output.delivery?.hd ?? output.candidate,
      fallback:
        output.delivery?.localFallback ??
        output.delivery?.localAsset ??
        output.delivery?.poster ??
        output.fallback,
      poster: output.delivery?.poster ?? output.poster,
    },
  ]),
);

const source = `// Generated by tools/unreal/generate_renderlab_preview_catalog.mjs. Do not edit.\n\nexport interface RenderLabCandidateEntry {\n  id: string;\n  phase: number;\n  screens: readonly string[];\n  kind: string;\n  placement?: "route-background" | "inline";\n  status: string;\n  decision?: string;\n  note?: string;\n  candidate?: string;\n  fallback?: string;\n  poster?: string;\n}\n\nexport const renderLabPreviewCatalog: Readonly<Record<string, RenderLabCandidateEntry>> = ${JSON.stringify(catalog, null, 2)};\n`;

await mkdir(new URL("../../src/generated/", import.meta.url), { recursive: true });
await writeFile(outputUrl, source, "utf8");
console.log(`Render Lab preview catalog generated: ${Object.keys(catalog).length} candidates.`);
