import { mkdir, readFile, writeFile } from "node:fs/promises";

const manifestUrl = new URL("./render-manifest.json", import.meta.url);
const outputUrl = new URL("../../src/generated/renderLabPreviewCatalog.ts", import.meta.url);
const manifest = JSON.parse(await readFile(manifestUrl, "utf8"));

const catalog = Object.fromEntries(
  manifest.outputs.map((output) => [
    output.id,
    {
      id: output.id,
      phase: output.phase,
      screens: output.screens ?? [],
      kind: output.kind,
      status: output.unreal?.status ?? "unknown",
      decision: output.review?.decision,
      note: output.review?.note,
      provenance: output.provenance,
      render: output.render,
      destination: output.integration?.destination,
      candidate: output.delivery?.hd,
      fallback:
        output.delivery?.localFallback ??
        output.delivery?.localAsset ??
        output.delivery?.poster,
      poster: output.delivery?.poster,
    },
  ]),
);

const source = `// Generated by tools/unreal/generate_renderlab_preview_catalog.mjs. Do not edit.\n\nexport interface RenderLabCandidateEntry {\n  id: string;\n  phase: number;\n  screens: readonly string[];\n  kind: string;\n  status: string;\n  decision?: string;\n  note?: string;\n  provenance?: {\n    sourceType: string;\n    package?: string;\n    license?: string;\n    sourceAssets?: readonly string[];\n    modifiedAssets?: readonly string[];\n  };\n  render?: {\n    localPath?: string;\n    resolution?: string;\n    durationSeconds?: number;\n    frameRate?: number;\n  };\n  destination?: string;\n  candidate?: string;\n  fallback?: string;\n  poster?: string;\n}\n\nexport const renderLabPreviewCatalog: Readonly<Record<string, RenderLabCandidateEntry>> = ${JSON.stringify(catalog, null, 2)};\n`;

await mkdir(new URL("../../src/generated/", import.meta.url), { recursive: true });
await writeFile(outputUrl, source, "utf8");
console.log(`Render Lab preview catalog generated: ${Object.keys(catalog).length} candidates.`);
