import { mkdir, readFile, writeFile } from "node:fs/promises";

const manifestUrl = new URL("./render-manifest.json", import.meta.url);
const outputUrl = new URL("../../src/generated/renderMediaCatalog.ts", import.meta.url);
const manifest = JSON.parse(await readFile(manifestUrl, "utf8"));
const shippableStatuses = new Set(["approved", "integrated"]);

const catalog = Object.fromEntries(
  manifest.outputs
    .filter((output) => shippableStatuses.has(output.unreal?.status))
    .map((output) => {
      const compactFallback =
        output.delivery?.localFallback ??
        output.delivery?.localAsset ??
        output.delivery?.poster;
      if (!compactFallback) {
        throw new Error(`${output.id}: approved media requires a compact local fallback`);
      }
      return [
        output.id,
        {
          kind: output.kind,
          hd: output.delivery.hd,
          fallback: compactFallback,
          poster: output.delivery.poster,
        },
      ];
    }),
);

const source = `// Generated by tools/unreal/generate_runtime_media_catalog.mjs. Do not edit.\n\nexport interface GeneratedRenderMediaEntry {\n  kind: string;\n  hd: string;\n  fallback: string;\n  poster?: string;\n}\n\nexport const renderMediaCatalog: Readonly<Record<string, GeneratedRenderMediaEntry>> = ${JSON.stringify(catalog, null, 2)};\n`;

if (process.argv.includes("--check")) {
  const existing = await readFile(outputUrl, "utf8").catch(() => "");
  if (existing !== source) {
    console.error("Runtime media catalog is stale. Run npm run generate:render-media.");
    process.exitCode = 1;
  } else {
    console.log(`Runtime media catalog valid: ${Object.keys(catalog).length} approved outputs.`);
  }
} else {
  await mkdir(new URL("../../src/generated/", import.meta.url), { recursive: true });
  await writeFile(outputUrl, source, "utf8");
  console.log(`Runtime media catalog generated: ${Object.keys(catalog).length} approved outputs.`);
}
